name: 'Install PHP Composer'
description: 'Github Composite action to install php composer'

runs:
  using: "composite"
  steps:
    - name: Install php composer
      run: |
        sudo apt-get update -y
        curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
        HASH='curl -sS https://composer.github.io/installer.sig'
        echo $HASH
        php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      shell: bash
